comit-network/waves

- waves/src/App.css
- waves/src/App.tsx
- waves/src/WalletBalance.tsx
New layout. Balances are buttons to show wallet.
> Show balance if wallet is unlocked

- elements-fun/src/encode.rs
- elements-fun/src/endian.rs
- elements-fun/src/lib.rs
- elements-fun/src/script.rs
- elements-fun/src/sighash.rs
- elements-fun/src/transaction.rs
d35a32f Merge pull request #64 from sanket1729/segwit_sighash
9d76ae6 Add legacy sighash
bbf2e67 Add endian file from upstream(not public)
2e93c12 Add more utility functions to script
609f298 Added segwit signature hash
0cfad67 Added sighashtype for transaction
git-subtree-dir: elements-fun
git-subtree-split: d35a32f2efbb3c59ac02db6c5655d96a7b61e5fa
> Squashed 'elements-fun/' changes from 4021b3b..d35a32f

- Cargo.lock
- waves/wallet/Cargo.toml
- waves/wallet/README.md
- waves/wallet/src/esplora.rs
- waves/wallet/src/wallet.rs
> Return amounts in `get_balances` formatted to nominal representation

- elements-fun/src/transaction.rs
- waves/wallet/README.md
- waves/wallet/src/esplora.rs
- waves/wallet/src/lib.rs
- waves/wallet/src/wallet.rs
> Introduce "withdraw all" functionality

- waves/wallet/src/esplora.rs
> Handle esplora returning a 404 for UTXOs of an address

- waves/wallet/README.md
- waves/wallet/src/esplora.rs
- waves/wallet/src/wallet.rs
> Fall back to a default fee rate if fee estimation using Esplora fails

- Cargo.lock
- bobtimus/Cargo.toml
- bobtimus/src/http.rs
- waves-scripts
- waves/.gitignore
- waves/build/.gitignore
- waves/src/index.tsx
I'm not sure if this is the best way to do this but it works. 
Bobtimus embeds the content of wave's build folder during build time. Which means, if the folder is not present, the build fails. I opted for checking this folder in and ignoring its content to enforce that this folder exists. 
Resolves #33
> Embed waves in bobtimus

- .gitignore
- waves-scripts
> Improve waves-script to allow for restarting Bobtimus.

- Cargo.lock
- bobtimus/Cargo.toml
- bobtimus/src/http.rs
- bobtimus/src/lib.rs
- bobtimus/src/problem.rs
- swap/Cargo.toml
- swap/src/lib.rs
I followed the approach we took in comit-rs (and c&p problem.rs).
The error looks like this: 
Server:
```bash
[2021-01-06T03:32:52Z INFO  bobtimus::problem] route failed because failed to calculate change amount for alice: The inputs contain an AssetId != 5ac9f65c0efcc4775e0baec4ec03abdde22473cd3cf33c0419ca290e0751b225.
```
Client: 
Resolves #92
> Return detailed error message to client using Http Error Codes.

- waves/src/App.test.tsx
- waves/src/App.tsx
- waves/src/theme.tsx
Resolves #105.
Resolves #104.
Unlock wallet: 
Swap Button disabled:
> Move new/unlock wallet to the top and disable swap button

- Cargo.lock
- Cargo.toml
- elements-fun/Cargo.toml
- elements-fun/src/address.rs
- waves/wallet/Cargo.toml
> Remove patched dependencies

- waves/src/App.tsx
- waves/src/ConfirmSwapDrawer.tsx
- waves/src/CreateWalletDrawer.tsx
- waves/src/UnlockWalletDrawer.tsx
- waves/src/WalletBalances.tsx
- waves/src/WalletDrawer.tsx
- waves/src/components/AssetSelect.tsx
- waves/src/components/AssetSelector.tsx
- waves/src/theme.tsx
Fixes #122.
I chose blue as our primary color because water is blue and the project is called waves.
Some screenshots:
> Reduce custom styling

- Cargo.lock
- extension/Cargo.toml
- extension/background/src/lib.rs
- extension/message_types/src/lib.rs
- extension/src/app.rs
- extension/src/components/wallet_details.rs
> Reintroduce withdraw all button 

- extension/wallet_lib/src/cache_storage.rs
- extension/wallet_lib/src/esplora.rs
- extension/wallet_lib/src/lib.rs
resolves #143
supersedes: #147
>  Use local storage to cache reqests in wallet. 

- extension/background/src/lib.rs
- extension/in_page/src/lib.rs
- extension/message_types/src/lib.rs
- extension/src/app.rs
- waves/src/App.tsx
- waves/src/wasmProxy.ts
It makes more sense to have the faucet in the webapp than in the browser extension as it is a _feature_ by bobtimus.
> Move faucet into webapp

- waves/src/App.tsx
> Conditionally rende faucet if in development mode

- e2e_tests/e2e_test_setup.sh
create a simple if-then condition to avoid having the user remembering the correct way to run the e2e tests locally
> simplified local test

- Cargo.lock
- e2e_tests/src/create_wallet.test.ts
- e2e_tests/src/e2e.test.ts
- e2e_tests/src/unlock_wallet.test.ts
- e2e_tests/src/utils.ts
- extension/src/components/Balances.tsx
- extension/wallet/Cargo.toml
- extension/wallet/src/lib.rs
- extension/wallet/src/wallet.rs
- extension/wallet/src/wallet/create_new.rs
follow-up PR from https://github.com/comit-network/waves/pull/191#discussion_r677959410 and https://github.com/comit-network/waves/pull/191#discussion_r677959597
> PR feedback

- extension/src/App.tsx
- extension/src/components/Balances.tsx
- extension/src/models.ts
- added title in wallet UI
- moved settings button into corner
- made balances less jumpy by sorting them alphabetically
- fixed ticker symbol to show L-USDT instead of a shit emoij :)
> Minor UI improvements

- Cargo.toml
- bobtimus/Cargo.toml
- coin_selection/Cargo.toml
- dprint.json
- estimate_transaction_size/Cargo.toml
- extension/wallet/Cargo.toml
The functionality of https://github.com/thomaseizinger/dprint-plugin-cargo-toml has been upstreamed to the official dprint toml plugin.
> Use official toml dprint plugin

- waves/src/App.tsx
- waves/src/Trade.tsx
- waves/src/components/AssetSelector.tsx
My OCD got triggered one time to often so I fixed two minor issues 😅
* When I looked that the UI for the first time (a while back) it was not clear what I would send and receive in the `Trade` view. 
* The navigation buttons not being aligned in the center
Note: Not proud of the negative margin weak to arrange those `You Send` and `You Receive` labels. It was the fastest way to get this the way I wanted (boxes algined with button in middle, labels in gray area above...). It does the job 🤷‍♂️
> You send you receive

- Cargo.lock
- Cargo.toml
- bobtimus/src/lib.rs
- coin_selection/Cargo.toml
- coin_selection/src/lib.rs
- estimate_transaction_size/Cargo.toml
- estimate_transaction_size/src/lib.rs
- extension/wallet/Cargo.toml
- extension/wallet/src/cache_storage.rs
- extension/wallet/src/esplora.rs
- extension/wallet/src/lib.rs
- extension/wallet/src/wallet.rs
- extension/wallet/src/wallet/create_new.rs
- extension/wallet/src/wallet/extract_loan.rs
- extension/wallet/src/wallet/extract_trade.rs
- extension/wallet/src/wallet/get_balances.rs
- extension/wallet/src/wallet/get_status.rs
- extension/wallet/src/wallet/get_transaction_history.rs
- extension/wallet/src/wallet/load_existing.rs
- extension/wallet/src/wallet/make_create_swap_payload.rs
- extension/wallet/src/wallet/make_loan_request.rs
- extension/wallet/src/wallet/repay_loan.rs
- extension/wallet/src/wallet/sign_and_send_swap_transaction.rs
- extension/wallet/src/wallet/sign_loan.rs
- extension/wallet/src/wallet/withdraw_everything_to.rs
Reverts comit-network/waves#202
Current master is broken due to this merge. Also see https://github.com/comit-network/waves/pull/250.
cc @rishflab
> Revert "Extract stateless functions into wallet library module"
