comit-network/waves

elements-harness/src/elementd_rpc.rs
elements-harness/src/image.rs

Initially I thought `regtest` is elements `regtest` mode but this seems to be wrong. Using a custom chain e.g. `elementsregtest` solves this problem. See here: https://docs.blockstream.com/liquid/node_setup.html
This seems to be the correct thing to do as the addresses generated in code by using something like this are accepted by the node.
```rust
let secp = elements::bitcoin::secp256k1::Secp256k1::new();
let (_private_key, public_key) =
secp.generate_keypair(&mut elements::bitcoin::secp256k1::rand::thread_rng());
let public_key = elements::bitcoin::PublicKey {
compressed: true,
key: public_key,
};
let target_address =
elements::Address::p2wpkh(&public_key, None, &elements::AddressParams::ELEMENTS);
let address_string = target_address.clone().to_string();
println!("address : {}", …
```

Use elementsregtest and make default wallet rich

---

elements-fun/src/address.rs
elements-fun/src/blech32.rs
elements-fun/src/block.rs
elements-fun/src/confidential.rs
elements-fun/src/dynafed.rs
elements-fun/src/encode.rs
elements-fun/src/fast_merkle_root.rs
elements-fun/src/internal_macros.rs
elements-fun/src/issuance.rs
elements-fun/src/lib.rs
elements-fun/src/slip77.rs
elements-fun/src/transaction.rs
elements-fun/src/wally.rs
swap/src/lib.rs
swap/src/states.rs

Make better use of the type system

---

elements-fun/Cargo.toml
elements-fun/README.md
elements-fun/src/confidential.rs
elements-fun/src/issuance.rs
elements-fun/src/transaction.rs
elements-fun/src/wally.rs
swap/src/lib.rs
swap/src/states.rs

We swing the magic modelling wand and produce two constructors on `TxOut` that make it a lot easier to produce valid transactions!

Do magic with the modelling wand

---

Cargo.lock
Cargo.toml
waves/.eslintignore
waves/wallet/src/wallet.rs

These linter errors prevented us from running `yarn build` once we actually include the WASM.

Fix linter errors

---

bobtimus/src/bin/fake_bobtimus.rs
bobtimus/src/lib.rs

Bobtimus can easily query the blockchain for all data it needs, hence
we can reduce bandwidth usage and simplify client implementations.

Change Bobtimus' API to accept an outpoint instead of TxIn and TxOut

---

.github/workflows/ci.yml

In order to debug the fuzzer locally, once has to load the crash
file in the debugger. As such, we upload the whole fuzzer workspace
as an artefact so it can be downloaded from the CI job.
Fixes #52.

Upload hfuzz_workspace in case the fuzzer fails

---

.github/workflows/ci.yml
Cargo.lock

Let's see what CI says about macos builds
Once: https://github.com/comit-network/rust-secp256k1-zkp/pull/8 was merged this PR should turn green.
We only build on MacOS and don't run tests because some tests require docker. See https://github.com/comit-network/droplet/issues/55

Add build matrix for 'normal' tests to also build on macos

---

waves/wallet/src/cache_storage.rs
waves/wallet/src/esplora.rs

We return an anyhow::Result from all the cache wrapper APIs.
This allows us to limit the usage of the error mapping macros to within
the cache wrapper.

Make working with caches more ergonomic

---

.github/workflows/ci.yml

FYI @bonomat 
We need to disable the cache because MacOS `tar` is broken :(

Disable cache on MacOS

---

waves-scripts

If not provided `ELEMENTS_CHAIN` defaults to `LIQUID`.

Set elements_chain env variable when starting waves

---

waves/wallet/src/wallet/get_balances.rs
waves/wallet/src/wallet/withdraw_everything_to.rs

`group_by` only groups "on-the-fly" and therefore does not work if
the iterator is not yet sorted.
`into_group_map` consumes the iterator instead and actually groups
all elements properly.

Replace `group_by` with `into_group_map`

---

.github/workflows/ci.yml
elements-fun/src/issuance.rs
waves/wallet/Cargo.toml
waves/wallet/build.rs
waves/wallet/src/esplora.rs
waves/wallet/src/lib.rs
waves/wallet/src/wallet.rs
waves/wallet/src/wallet/make_create_swap_payload.rs
waves/wallet/src/wallet/withdraw_everything_to.rs

We add a buildscript that reads the env variables, verifies them and
writes them to a Rust file as constants which we can include at
build time.
This allows us to verify all the configuration parameters at build time
instead of being surprised at runtime with an error like
"invalid elements chain".

Replace `Lazy` statics with constants

---

bobtimus/src/bin/fake_bobtimus.rs
bobtimus/src/http.rs
waves/src/Bobtimus.tsx
waves/src/SwapWithWallet.tsx
waves/src/WalletInfo.tsx
waves/src/index.tsx

This PR adds `api` prefix to all Bobtimus API. I've extracted a helper file `Bobtimus.tsx` in waves which should serve as a onestop place to interact with Bobtimus.
It also enables all cors headers for `fake_bobtimus` which simplifies development. 
Resolves #77

Update bobtimus api and extract helper in waves

---

Cargo.lock
bobtimus/src/http.rs
elements-fun/src/lib.rs
waves/src/Bobtimus.tsx
waves/src/SwapWithWallet.tsx
waves/src/wasmProxy.ts
waves/wallet/src/lib.rs
waves/wallet/src/wallet.rs
waves/wallet/src/wallet/decompose_transaction.rs

I decided to change the serialisation format for the transaction because deserialising the JSON was failing on waves wallet. I could not reproduce the error via unit tests ("malformed pedersen commitment") so I went for a quick fix. It may be worth it to get to bottom of it.

Decompose Bob's transaction into our unblinded inputs and outputs

---

waves-scripts
waves/src/App.tsx

Point user to local blockexplorer instead of blockstream.info on regtest

---

bobtimus/src/bin/bobtimus.rs
bobtimus/src/bin/fake_bobtimus.rs
bobtimus/src/http.rs
bobtimus/src/lib.rs

Bobtimus holds an instance of rng initialised at start-up. Every time we receive a request, we clone our instance of Bobtimus and therefore the instance of rng itself. Any state changes to the rng (which happen during usage) thereby did not affect the original prototype of Bobtimus. As a result, any future request started with exactly the same rng state and therefore produced the same sequence of random numbers.
This led to conflicting blinding factors between inputs and outputs.
Fixes #91.

Stop making too many evil clones of Bob

---

waves/src/App.test.tsx
waves/src/App.tsx
waves/src/components/AssetSelector.tsx

The problem was that the component `NumberInput` propagates the value as a string or as a number up onChange. Since we dropped/ignored the string any added decimal points were overwritten.
Resolves #103

Fix decimal number input issue.

---

bobtimus/src/http.rs
waves/package.json
waves/src/App.tsx

This applies to all assets apart from index.html.
Unfortunately, we need to add a hook to the app to redirect from
/app to / to make it work with the webpack-dev-server because
setting `homepage` in `package.json` makes `react-scripts` open
the browser on `http://localhost:3004/app`.
I hesitated to guard this piece of code with `if env == development`
because I think it might actually also be useful in production.
If someone for whatever reasons investigates our routes and finds
`/app`, we just send them back to the root.
Resolves #79.

Serve frontend under /app namespace

---

.github/workflows/ci.yml
waves/wallet/.cargo/config.toml

Enable caching of Rust artifacts on MacOS

---

extension/in_page/src/lib.rs
waves/src/App.tsx
waves/src/wasmProxy.ts

For this to work we must use `&JsValue::from(liquid)` and not `&JsValue::from_serde(&liquid)` (see https://github.com/rustwasm/wasm-bindgen/issues/2493).

Add liquid field to window object instead of methods

---

.github/workflows/ci.yml

We can add a MacOS ci build for the whole repository once we've removed the libraries (swap/covenants/etc). These modules use docker for their tests which is not available on MacOS. 
Note: LLVM 12 is already installed on MacOS (see [here](https://github.com/bonomat/droplet/runs/3074604513?check_suite_focus=true)), hence we only need to overwrite the environment variables.
CC: @rishflab / @thomaseizinger : this might be interesting for you.

Add MacOS ci builds for wasm wallet tests.

---

.github/workflows/ci.yml
e2e_tests/.gitignore
e2e_tests/e2e_test_setup.sh
e2e_tests/nigiri/docker-compose.yml
e2e_tests/nigiri/liquid-config/elements.conf
e2e_tests/package.json
e2e_tests/readme.md
e2e_tests/src/borrow.test.ts
e2e_tests/src/create_wallet.test.ts
e2e_tests/src/unlock_wallet.test.ts
e2e_tests/src/usdt-btc_buy.test.ts
e2e_tests/src/usdt-btc_sell.test.ts
e2e_tests/src/utils.ts
extension/src/components/CreateWallet.tsx

This PR aims at having deterministic e2e tests. For that we remove as much randomness from the tests and move it into the e2e_test_setup.sh. 
- each test has its own file and own setup. With this approach we don't run into the danger of reusing the same state in different tests which can make problems
- each test uses its own wallet. that way a test does not spend utxos which are used elsewhere
- tests are run sequentially. By having a separate file for each test we can enforce that the tests are run sequentially. This is slower but removes randomness.
- No faucets in tests: by moving the funding of the test wallets into the e2e test setup we remove one more source of randomness.

Deterministic e2e test setup

---

waves/src/Borrow.tsx

For wrapping a custom component with a tooltip on has to implement forwardRef for the component. Since this is a bit cumbersome another workaround is to wrap the custom component with a Box.
From chakra-ui documentation: If the Tooltip is wrapping a functional component, ensure that the functional component accepts a ref using forwardRef.

Fix tooltip display

---

Cargo.lock
bobtimus/Cargo.toml
bobtimus/proptest-regressions/lib.txt
bobtimus/src/database.rs
bobtimus/src/elements_rpc.rs
bobtimus/src/lib.rs
bobtimus/src/loan.rs
coin_selection/Cargo.toml
coin_selection/src/lib.rs
extension/src/background/index.ts
extension/src/components/OpenLoans.tsx
extension/src/wasmProxy.ts
extension/wallet/Cargo.toml
extension/wallet/src/esplora.rs
extension/wallet/src/lib.rs
extension/wallet/src/wallet.rs
extension/wallet/src/wallet/extract_loan.rs
extension/wallet/src/wallet/make_create_swap_payload.rs
extension/wallet/src/wallet/make_loan_request.rs
waves/src/App.test.tsx
waves/src/App.tsx
waves/src/Bobtimus.tsx
waves/src/Borrow.tsx
waves/src/waves-provider/index.d.ts
waves/src/waves-provider/wavesProvider.ts

Instead of calculating the absolute timelock for the loan offer (which would mean that it already "declines" while the user is still chosing a loan) we use relative loan term in days and the absolute timelock is calculated by the lender upon loan request. The borrower has to check that the timelock is as expected when signing the loan (has to check anyway).
includes upgrading to baru `0.2` :)
fixes #220

Lender creates timelock

---

extension/wallet/src/wallet/repay_loan.rs

Resolves #201
Use `filter` instead of `take_while`.
`Take_while` will stop as soon as the first closure returns false. That's why loans further down in the list vanished if you settled the first loan.
Signed-off-by: Philipp Hoenisch <philipp@hoenisch.at>

Fix vanishing loans bug

---

Cargo.lock
bobtimus/Cargo.toml
bobtimus/proptest-regressions/lib.txt
bobtimus/src/amounts.rs
bobtimus/src/lib.rs
bobtimus/src/loan.rs
extension/src/background-proxy.ts
extension/src/background/index.ts
extension/src/components/ConfirmLoanWizard.tsx
extension/src/components/OpenLoans.tsx
extension/src/wasmProxy.ts
extension/wallet/Cargo.toml
extension/wallet/src/esplora.rs
extension/wallet/src/lib.rs
extension/wallet/src/wallet/make_loan_request.rs
waves/src/App.test.tsx
waves/src/App.tsx
waves/src/Bobtimus.tsx
waves/src/Borrow.tsx

Lender now includes the loan calculations and the validation of the loan.
I clicked it through and it looks sane :)
To be done in follow ups:
- Send **all** amounts in sats and do conversion on UI side (did not tackle all amounts yet)
- Validation step for the loan term
- Upgrade the UI so the borrower can select values

Upgrade Botimus to handle loan calc and validation
